blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discord
    url: https://discord.gg/YKwjt5vuKr
    about: Join our Discord for help and discussions!
  - name: ğŸ’¼ Slack
    url: https://dub.sh/browserOS-slack
    about: Join our Slack for help and queries!
  - name: ğŸ’¡ Feature Requests
    url: https://github.com/khadem-ai/Khadem/issues/99
    about: Have an idea? Share it here and vote on others
  - name: ğŸ“š Documentation
    url: https://docs.khadem.com/
    about: Find setup guides and learn how to use Khadem
